<a href="https://www.kaggle.com/code/quctngngvng/autoconfig?scriptVersionId=145923819" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
import tensorflow as tf

In [2]:
from transformers import GPT2Config, GPT2Model
from transformers import AutoConfig, AutoModelForMultipleChoice
from transformers import AutoTokenizer,AutoConfig,AutoModel

In [ ]:
from transformers import AutoConfig, TFAutoModel,AutoModel

config = AutoConfig.from_pretrained('bert-base-uncased')

model = TFAutoModel.from_config(config)

model.compile(
    loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
    optimizer=tf.keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("VietAI/gpt-neo-1.3B-vietnamese-news")

In [ ]:
confix_Viet = AutoConfig.from_pretrained("VietAI/gpt-neo-1.3B-vietnamese-news")

In [ ]:
confix_Viet

In [ ]:
model2 = AutoModel.from_config(confix_Viet)

In [ ]:
model2

In [ ]:
confix_Viet.architectures[0] = 'gpt2'

In [ ]:
model = AutoModel.from_config(confix_Viet)

In [ ]:
model

In [ ]:


# Initializing a GPT2 configuration
configuration = GPT2Config()

In [ ]:
configuration

In [ ]:
model.build()

In [ ]:
model.summary()

In [ ]:


# Download configuration from huggingface.co and cache.
config = AutoConfig.from_pretrained("bert-base-cased")
model = AutoModelForMultipleChoice.from_config(config)

In [ ]:
model

In [ ]:
config = AutoConfig.from_pretrained("mr4/phobert-base-vi-sentiment-analysis")

In [ ]:
tokenni = AutoTokenizer.from_pretrained("mr4/phobert-base-vi-sentiment-analysis")

In [ ]:
tokenni

In [ ]:
config

In [ ]:
multipleChoiceModel = AutoModelForMultipleChoice.from_config(config)

In [ ]:
config

# TEST PRETRAIN MODEL VIET

In [ ]:
tokenizerViet = AutoTokenizer.from_pretrained('mr4/phobert-base-vi-sentiment-analysis')

In [ ]:
tokenizerViet

In [ ]:
configBase = AutoConfig.from_pretrained('bert-base-cased')

In [ ]:
configBase

In [ ]:
tokenizerViet.model_max_length = 768

In [ ]:
tokenizerViet

In [ ]:
tokenizerViet_config = {
    "vocab_file": tokenizerViet.vocab_files_names["vocab_file"],
    "merges_file": tokenizerViet.vocab_files_names["merges_file"],
    "tokenizer_class": type(tokenizerViet).__name__,
}

In [ ]:
configBase.tokenizer_class = tokenizerViet_config

In [ ]:
configBase.model_type

In [ ]:
configBase

In [ ]:
model = AutoModel.from_config(configBase)

In [ ]:
tokenizerViet.push_to_hub(repo_id = 'VuongQuoc/bert-base-VN',token = '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')

In [ ]:
model.push_to_hub(repo_id = 'VuongQuoc/bert-base-VN',token = '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')

**Test push mode and token VI**

In [ ]:
config = AutoConfig.from_pretrained('VuongQuoc/bert-base-VN')

In [ ]:
print(config.finetuning_task)

In [ ]:
config.num_labels

In [3]:
tokenizer = AutoTokenizer.from_pretrained('VuongQuoc/bert-base-VN')

In [ ]:
# model = AutoModel.from_pretrained('VuongQuoc/bert-base-VN')

In [4]:
val = "Ngày hôm này thế nào"
raw_inputs = [val]
inputs = tokenizer(raw_inputs, padding=True,
                   truncation=False, return_tensors="pt")

In [ ]:
out = model(**inputs)

In [ ]:
out['last_hidden_state'].shape

In [ ]:
# config_multicchoice = AutoConfig.from_pretrained('VuongQuoc/bert-base-VN')

In [ ]:
# config_multicchoice.vocab_size = tokenizer.vocab_size +1
# config_multicchoice.push_to_hub('VuongQuoc/bert-base-VN',token = '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')

In [6]:
modelChoice = AutoModelForMultipleChoice.from_pretrained('VuongQuoc/bert-base-VN',ignore_mismatched_sizes=True)

Some weights of BertForMultipleChoice were not initialized from the model checkpoint at VuongQuoc/bert-base-VN and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of BertForMultipleChoice were not initialized from the model checkpoint at VuongQuoc/bert-base-VN and are newly initialized because the shapes did not match:
- embeddings.word_embeddings.weight: found shape torch.Size([28996, 768]) in the checkpoint and torch.Size([64001, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [7]:
modelChoice

BertForMultipleChoice(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(64001, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, element

In [52]:
prompt = "Bác Hồ là người nước nào ?."
candidate1 = "Việt Nam"
candidate2 = "Mỹ"
candidate3 = 'Việt Nam'

In [53]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("VuongQuoc/bert-base-VN")
inputs = tokenizer([[prompt, candidate1], [prompt, candidate2],[prompt, candidate3]], return_tensors="pt", padding=True)


In [54]:
inputs['input_ids'] = inputs['input_ids'].unsqueeze(0)
inputs['token_type_ids'] = inputs['token_type_ids'].unsqueeze(0)
inputs['attention_mask'] = inputs['attention_mask'].unsqueeze(0)

In [55]:
inputs['input_ids'].shape

torch.Size([1, 3, 14])

In [56]:
import torch
labels = torch.tensor(0).unsqueeze(0)

In [58]:
labels

tensor([0])

In [59]:
out = modelChoice(**inputs)

In [60]:
out

MultipleChoiceModelOutput(loss=None, logits=tensor([[ 0.0421, -0.0345,  0.0421]], grad_fn=<ViewBackward0>), hidden_states=None, attentions=None)

In [61]:
out = modelChoice(**inputs,labels = labels)

In [62]:
out.logits

tensor([[ 0.0421, -0.0345,  0.0421]], grad_fn=<ViewBackward0>)

In [63]:
out.logits

tensor([[ 0.0421, -0.0345,  0.0421]], grad_fn=<ViewBackward0>)

In [68]:
from torch import nn
import torch.nn.functional as F

https://pytorch.org/docs/stable/generated/torch.nn.NLLLoss.html

In [65]:
m = nn.LogSoftmax(dim=1)
loss = nn.NLLLoss()

In [73]:
softmax = F.softmax(out.logits)
torch.log(softmax)
print(out.logits,m(out.logits))

tensor([[ 0.0421, -0.0345,  0.0421]], grad_fn=<ViewBackward0>) tensor([[-1.0737, -1.1503, -1.0737]], grad_fn=<LogSoftmaxBackward0>)


/tmp/ipykernel_2290/700195406.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  softmax = F.softmax(out.logits)


In [39]:
output_loss = loss(m(out.logits), labels)

In [40]:
output_loss

tensor(0.7210, grad_fn=<NllLossBackward0>)

In [79]:
target = torch.empty(5, 8, 8, dtype=torch.long).random_(0, 3)

tensor([[[1, 1, 0, 1, 0, 0, 0, 0],
         [0, 2, 2, 1, 0, 1, 1, 2],
         [1, 0, 1, 1, 0, 0, 2, 1],
         [2, 0, 2, 0, 1, 0, 0, 0],
         [1, 1, 2, 1, 2, 2, 2, 1],
         [0, 1, 0, 1, 2, 1, 2, 2],
         [0, 2, 1, 0, 0, 0, 0, 0],
         [1, 1, 0, 2, 2, 2, 2, 2]],

        [[1, 1, 0, 2, 0, 0, 1, 2],
         [0, 1, 0, 0, 1, 0, 1, 2],
         [0, 1, 1, 0, 0, 0, 0, 2],
         [0, 1, 2, 1, 1, 2, 2, 2],
         [2, 1, 2, 0, 2, 2, 2, 0],
         [0, 2, 1, 2, 2, 2, 1, 1],
         [0, 0, 2, 1, 2, 2, 1, 1],
         [2, 2, 0, 1, 2, 2, 1, 0]],

        [[2, 2, 2, 2, 1, 0, 2, 2],
         [1, 2, 1, 2, 2, 0, 0, 0],
         [0, 1, 2, 0, 0, 1, 2, 2],
         [0, 1, 1, 2, 0, 1, 1, 0],
         [2, 2, 0, 2, 1, 0, 2, 1],
         [2, 2, 2, 1, 1, 1, 1, 0],
         [1, 2, 0, 1, 0, 1, 1, 0],
         [2, 0, 0, 0, 2, 0, 2, 0]],

        [[2, 0, 0, 1, 0, 0, 0, 0],
         [0, 1, 2, 2, 0, 0, 0, 1],
         [2, 1, 0, 0, 0, 2, 0, 0],
         [0, 1, 2, 1, 2, 1, 2, 2],
         [2, 1

In [78]:
target.shape  

torch.Size([5, 8, 8])